name: tfm_segmentacion_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cudatoolkit=11.8
  - pandas=2.0.0
  - matplotlib=3.7.0
  - scikit-learn=1.3.0
  - scikit-image=0.21.0
  - jupyter=1.0.0
  - tqdm=4.65.0
  - pyyaml=6.0
  - seaborn=0.12.2
  - nibabel=5.1.0
  - plotly=5.14.1
  - scipy=1.11.0
  
  - pip:
    - numpy==1.23.5
    - albumentations==1.3.0
    - opencv-python==4.8.0.76
    - tensorboard==2.13.0
    - wandb==0.15.8
    - fastapi>=0.104.0
    - uvicorn[standard]>=0.24.0
    - python-multipart>=0.0.6
    - Pillow>=10.0.0